name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.ftp://145.79.212.169 }}
          username: ${{ secrets.u323182147 }}
          password: ${{ secrets.Chennabasappa@123 }}
          local-dir: ./
          server-dir: /public_html/apps/meesho-image-generator/
          exclude: |
            **/.git*
            **/.git*/**
            **/config.php
            **/node_modules/**